### PR TITLE
Reduce header size

### PR DESCRIPTION
**Pull request by lgeiger**
This PR simplifies the header so it takes up less screen space:

Before | After
--- | ---
black now sh__version stable state _td6wfoaaatm1rrgagaharyaaab0l-wj4arxampdad2iimzxl1n_wlkpinbfoxifdftatvkgvehsharyj9ypldvwba7lhgo8bvrqqdilptgsfdkl-ha7efp0ma6ly_06icekivsj3bpoicjm9wu1vjld7l3qd5xtmo78lqthf9uibgwcwcd16lbon0jk8rhhx_gf2clysdjtv|localhost_3000__version stable state _td6wfoaaatm1rrgagaharyaaab0l-wj4arxampdad2iimzxl1n_wlkpinbfoxifdftatvkgvehsharyj9ypldvwba7lhgo8bvrqqdilptgsfdkl-ha7efp0ma6ly_06icekivsj3bpoicjm9wu1vjld7l3qd5xtmo78lqthf9uibgwcwcd16lbon0jk8rhhx_gf2cl 1

### CODE REVIEW

**Comment by jpadilla** [comment]
@lgeiger can we make the header and footer the same height?

**Comment by lgeiger** [comment]
> @lgeiger can we make the header and footer the same height?

Thanks for the fast review! I tried that but it looked a bit weird with the existing buttons.
But I can look a closer look at it.

**Comment by lgeiger** [comment]
>  I tried that but it looked a bit weird with the existing buttons.

I changed the padding a bit and it actually doesn't look to bad. I updated the screenshot above.

**Comment by jpadilla** [comment]
@lgeiger lgtm thanks! 🎉

**Pull request merged**
